# add fox label when "fox" is found
label-test:fox:
  pattern: fox
# add cat label when "cat" is found
label-test:cat:
  pattern: cat
# add cow label when "cow" is found.
# remove cow label if "cow" is missing.
label-test:cow:
  pattern: cow
  removeOnMissing: true
# add regex label when the specified regular expression pattern is matching.
label-test:regex:
  pattern: "[Tt]he.*\\."
label-test:pirate:
  # To detect pirates in issue, check any appearences of `Ahoy`, `matey`, `Rrrr!` and so on.
  any:
    - "[Aa]hoy"
    - "[Mm]atey"
    - ([AR]a*|Ya+)rrr+!
    - matchLabel: |-
        ^label-test:pirate:

# If the pirate talks about "rum", he must be a caribbean pirate.
label-test:pirate:caribbean:
  - label: label-test:rum
  - any:
    - "[Aa]hoy"
    - "[Mm]atey"
    - ([AR]a*|Ya+)rrr+!
