# add fox label when "fox" is found
label-test:fox:
  pattern: fox
# add cat label when "cat" is found
label-test:cat:
  pattern: cat
# add cow label when "cow" is found.
# remove cow label if "cow" is missing.
label-test:cow:
  pattern: cow
  removeOnMissing: true
# add regex label when the specified regular expression pattern is matching.
label-test:regex:
  pattern: "[Tt]he.*\\."
