version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix(deps)"
      prefix-development: "chore(deps)"
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(ci)"
      prefix-development: "chore(ci)"
