branches:
  - release
tagFormat: "v${version}"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/github"
    - assets:
      - dist/**
      - action.yaml
  - "@semantic-release/changelog"
