name: "Auto Labeling"
on:
  issues:
    types: [opened, edited]
permissions: write-all
jobs:
  mark:
    runs-on: ubuntu-latest
    steps:
      - uses: oakcask/github-action-auto-label-issue@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/auto-label.yaml
